import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';
import {controlSource,route} from './control.mjs';
function realm(memory=8,cpu=8){class Navigator{};if(memory!==null)Object.defineProperty(Navigator.prototype,'deviceMemory',{configurable:true,get:()=>memory});Object.defineProperty(Navigator.prototype,'hardwareConcurrency',{configurable:true,get:()=>cpu});
  const navigator=new Navigator();Object.assign(navigator,{languages:['en-US']});
  return vm.createContext({Navigator,navigator,location:{href:'file:///android_asset/expanded_probe.html',origin:'file://'},document:{readyState:'loading'},performance:{timeOrigin:1},screen:{width:1,height:1,colorDepth:24},devicePixelRatio:1,isSecureContext:true});}
test('sham preserves descriptors; only designated endpoint is modified',()=>{const a=realm(),b=realm(),d=Object.getOwnPropertyDescriptor(a.Navigator.prototype,'deviceMemory');vm.runInContext(controlSource({}),a);assert.deepEqual(Object.getOwnPropertyDescriptor(a.Navigator.prototype,'deviceMemory'),d);vm.runInContext(controlSource({deviceMemory:16,hardwareConcurrency:48}),b);assert.equal(a.navigator.deviceMemory,8);assert.equal(b.navigator.deviceMemory,16);vm.runInContext('__restoreResource()',b);assert.equal(b.navigator.deviceMemory,8);assert.equal(Object.hasOwn(b.navigator,'deviceMemory'),false);});
test('missing memory is never injected, CPU may change independently',()=>{const x=realm(null);vm.runInContext(controlSource({deviceMemory:16,hardwareConcurrency:48}),x);assert.equal('deviceMemory' in x.navigator,false);assert.equal(x.navigator.hardwareConcurrency,48);assert.equal(x.__resourceControl.applied.join(','),'hardwareConcurrency');});
test('4 equals baseline or downward change; no hidden retargeting',()=>{for(const n of [4,8]){const x=realm(n);vm.runInContext(controlSource({deviceMemory:4}),x);assert.equal(x.__resourceControl.before.resources.deviceMemory.value,n);assert.equal(x.navigator.deviceMemory,4);assert.equal(x.navigator.hardwareConcurrency,8);vm.runInContext('__restoreResource()',x);assert.equal(x.navigator.deviceMemory,n);}});
test('routes fixed, normal phases no getters',()=>{assert.deepEqual(route({scenario:'A_APP_RESOURCE',phase:'change'}).targets,{deviceMemory:16,hardwareConcurrency:48});assert.deepEqual(route({scenario:'N_BROWSER_SHAM',phase:'change'}).targets,{});assert.deepEqual(route({scenario:'A_BROWSER_MEMORY4',phase:'post'}).targets,{});assert.throws(()=>controlSource({deviceMemory:2}));});
