#!/usr/bin/env python3
"""Score grouped evidence rows with GLM-5.2.

The script reads evidence JSONL generated by prepare_validation_assets.py and
asks GLM for six 0-100 group risk scores. It is resumable by evidence_id and
does not persist API keys.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
DEFAULT_EVIDENCE = SCRIPT_DIR / "llm_group_evidence.jsonl"
DEFAULT_RULE_KB = REPO_ROOT / "scoring" / "rule_knowledge_base.json"
DEFAULT_OUTPUT = SCRIPT_DIR / "outputs" / "glm52_group_scores_k1.jsonl"
DEFAULT_ENDPOINT = "https://open.bigmodel.cn/api/paas/v4/chat/completions"

GROUP_SCORE_KEYS = [
    "native_web_score",
    "native_webview_score",
    "webview_web_score",
    "tri_layer_score",
    "physical_runtime_score",
    "attack_scenario_score",
]

GROUP_REASON_KEYS = [
    "native_web",
    "native_webview",
    "webview_web",
    "tri_layer",
    "physical_runtime",
    "attack_scenario",
]


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    if not rows:
        raise ValueError(f"No rows found in {path}")
    return rows


def load_manifest_filter(path: Path | None, filter_name: str | None) -> set[str] | None:
    if not path or not filter_name:
        return None
    selected: set[str] = set()
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        if filter_name not in reader.fieldnames:
            raise ValueError(f"{filter_name} not found in manifest columns: {reader.fieldnames}")
        for row in reader:
            if str(row.get(filter_name, "")).strip().lower() in {"1", "true", "yes"}:
                selected.add(row["evidence_id"])
    return selected


def compact_rule_kb(rule_kb: dict[str, Any]) -> dict[str, Any]:
    return {
        "name": rule_kb.get("name"),
        "version": rule_kb.get("version"),
        "field_conventions": rule_kb.get("field_conventions", {}),
        "score_bands": rule_kb.get("score_bands", []),
        "evaluation_order": rule_kb.get("evaluation_order", []),
        "rules": rule_kb.get("rules", []),
        "output_contract": rule_kb.get("output_contract", {}),
    }


def build_system_prompt(rule_kb: dict[str, Any]) -> str:
    rules_json = json.dumps(compact_rule_kb(rule_kb), ensure_ascii=False, indent=2)
    return f"""
你是 HybridGuard 的离线分组风险评分引擎。你将接收一条设备指纹的六组证据摘要。
请严格依据下方【综合规则知识库】分别判断每个证据组的风险强度。

评分方向必须统一：
0 = 低风险 / 一致 / 没有异常
100 = 高风险 / 明显矛盾 / 强攻击证据

评分原则：
1. 一票否决、高危模拟器、无头浏览器、接口重放等强证据应优先体现在 tri_layer_score 和 attack_scenario_score 中。
2. ADB、debuggable、cleartext、屏幕高度误差、Web deviceMemory 粗粒度差异、Chrome 小版本差异不能单独判为高危。
3. Google 官方知识只用于理解字段语义、安全背景和容错边界；不要把官方文档解释成 Google 官方风险分数。
4. 当前数据没有 Play Integrity verdict、Key Attestation 证书链或 WebView URL/origin 时，不要在理由中声称这些强证据已经命中。
5. 每个分组理由只写一句中文短理由，说明该组最关键的证据。

【综合规则知识库 JSON】
{rules_json}

输出必须是纯 JSON，且只包含以下字段：
{{
  "native_web_score": 0,
  "native_webview_score": 0,
  "webview_web_score": 0,
  "tri_layer_score": 0,
  "physical_runtime_score": 0,
  "attack_scenario_score": 0,
  "group_reasons": {{
    "native_web": "一句中文短理由",
    "native_webview": "一句中文短理由",
    "webview_web": "一句中文短理由",
    "tri_layer": "一句中文短理由",
    "physical_runtime": "一句中文短理由",
    "attack_scenario": "一句中文短理由"
  }}
}}

不要输出推理过程、Markdown、代码块或额外解释。
所有 score 必须是 0 到 100 的整数。
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Score grouped evidence with Zhipu GLM.")
    parser.add_argument("--evidence", default=str(DEFAULT_EVIDENCE), help="Evidence JSONL.")
    parser.add_argument("--rule-kb", default=str(DEFAULT_RULE_KB), help="Rule KB JSON path.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Output JSONL.")
    parser.add_argument("--endpoint", default=DEFAULT_ENDPOINT, help="Zhipu endpoint.")
    parser.add_argument("--model", default="glm-5.2", help="Model name.")
    parser.add_argument("--knowledge-version", default="K1_official", help="Ablation label.")
    parser.add_argument("--limit", type=int, default=None, help="Optional row limit.")
    parser.add_argument("--max-tokens", type=int, default=768, help="Max output tokens.")
    parser.add_argument("--temperature", type=float, default=0.1, help="Sampling temperature.")
    parser.add_argument("--timeout", type=int, default=90, help="HTTP timeout seconds.")
    parser.add_argument("--retries", type=int, default=2, help="Retry count per row.")
    parser.add_argument("--response-format-json", action="store_true", help="Request JSON mode.")
    parser.add_argument("--disable-thinking", action="store_true", help="Disable thinking if supported.")
    parser.add_argument("--api-key-file", default=None, help="File containing only API key.")
    parser.add_argument("--api-key-stdin", action="store_true", help="Read API key from stdin.")
    parser.add_argument("--manifest", default=None, help="Optional sample manifest CSV.")
    parser.add_argument(
        "--manifest-filter",
        default=None,
        help="Boolean manifest column to select, e.g. boundary_candidate.",
    )
    parser.add_argument(
        "--include-augmented",
        action="store_true",
        help="Allow augmented evidence rows. Defaults to originals only.",
    )
    return parser.parse_args()


def get_api_key(args: argparse.Namespace) -> str:
    if args.api_key_stdin:
        if sys.stdin.isatty():
            import termios

            fd = sys.stdin.fileno()
            old_attrs = termios.tcgetattr(fd)
            try:
                new_attrs = termios.tcgetattr(fd)
                new_attrs[3] = new_attrs[3] & ~termios.ECHO
                termios.tcsetattr(fd, termios.TCSADRAIN, new_attrs)
                api_key = sys.stdin.readline().strip()
            finally:
                termios.tcsetattr(fd, termios.TCSADRAIN, old_attrs)
                print()
        else:
            api_key = sys.stdin.readline().strip()
        if not api_key:
            raise ValueError("Empty API key from stdin.")
        return api_key
    if args.api_key_file:
        return Path(args.api_key_file).read_text(encoding="utf-8").strip()
    api_key = os.environ.get("ZHIPU_API_KEY", "").strip()
    if not api_key:
        raise ValueError("Missing API key. Use ZHIPU_API_KEY, --api-key-file, or --api-key-stdin.")
    return api_key


def read_processed_ids(path: Path) -> set[str]:
    processed = set()
    if not path.exists():
        return processed
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            try:
                item = json.loads(line)
            except json.JSONDecodeError:
                continue
            if item.get("evidence_id") and not item.get("error"):
                processed.add(str(item["evidence_id"]))
    return processed


def extract_json(text: str) -> dict[str, Any]:
    text = text.strip()
    try:
        parsed = json.loads(text)
        validate_result(parsed)
        return parsed
    except (json.JSONDecodeError, ValueError):
        pass

    matches = re.findall(r"\{.*\}", text, flags=re.DOTALL)
    for candidate in reversed(matches):
        try:
            parsed = json.loads(candidate)
            validate_result(parsed)
            return parsed
        except (json.JSONDecodeError, ValueError):
            continue
    raise ValueError(f"Could not parse grouped-score JSON from response: {text[:300]}")


def validate_result(parsed: dict[str, Any]) -> None:
    for key in GROUP_SCORE_KEYS:
        if key not in parsed:
            raise ValueError(f"Missing {key}")
        score = int(parsed[key])
        if score < 0 or score > 100:
            raise ValueError(f"{key} out of range: {score}")
    reasons = parsed.get("group_reasons")
    if not isinstance(reasons, dict):
        raise ValueError("Missing group_reasons object")
    for key in GROUP_REASON_KEYS:
        if key not in reasons:
            raise ValueError(f"Missing group_reasons.{key}")


def normalized_result(parsed: dict[str, Any]) -> dict[str, Any]:
    return {
        **{key: max(0, min(100, int(parsed[key]))) for key in GROUP_SCORE_KEYS},
        "group_reasons": {
            key: str(parsed.get("group_reasons", {}).get(key, "")) for key in GROUP_REASON_KEYS
        },
    }


def call_glm(
    args: argparse.Namespace,
    api_key: str,
    system_prompt: str,
    evidence_row: dict[str, Any],
) -> tuple[dict[str, Any], str]:
    request_body: dict[str, Any] = {
        "model": args.model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {
                "role": "user",
                "content": "请为以下六组证据分别输出风险子分数：\n"
                + json.dumps(evidence_row["prompt_payload"], ensure_ascii=False, indent=2),
            },
        ],
        "temperature": args.temperature,
        "max_tokens": args.max_tokens,
        "stream": False,
    }
    if args.response_format_json:
        request_body["response_format"] = {"type": "json_object"}
    if args.disable_thinking:
        request_body["thinking"] = {"type": "disabled"}

    raw = json.dumps(request_body, ensure_ascii=False).encode("utf-8")
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}",
    }

    last_error: Exception | None = None
    for attempt in range(1, args.retries + 2):
        try:
            req = urllib.request.Request(args.endpoint, data=raw, headers=headers, method="POST")
            with urllib.request.urlopen(req, timeout=args.timeout) as response:
                payload = json.loads(response.read().decode("utf-8"))
            message = payload["choices"][0].get("message", {})
            candidate_texts = [
                message.get("content", ""),
                message.get("reasoning_content", ""),
                message.get("reasoning", ""),
                message.get("output_text", ""),
            ]
            content = next(
                (text for text in candidate_texts if isinstance(text, str) and text.strip()), ""
            )
            if not content:
                preview = json.dumps(message, ensure_ascii=False)[:800]
                raise ValueError(f"Empty assistant message. message_preview={preview}")
            return normalized_result(extract_json(content)), content
        except (urllib.error.URLError, urllib.error.HTTPError, KeyError, ValueError) as exc:
            last_error = exc
            if attempt <= args.retries:
                time.sleep(min(2**attempt, 10))
    raise RuntimeError(f"GLM call failed after retries: {last_error}")


def main() -> None:
    args = parse_args()
    api_key = get_api_key(args)
    evidence_rows = load_jsonl(Path(args.evidence))
    selected_ids = load_manifest_filter(
        Path(args.manifest) if args.manifest else None,
        args.manifest_filter,
    )
    if selected_ids is not None:
        evidence_rows = [row for row in evidence_rows if row["evidence_id"] in selected_ids]
    if not args.include_augmented:
        evidence_rows = [row for row in evidence_rows if not row.get("is_augmented")]
    if args.limit is not None:
        evidence_rows = evidence_rows[: args.limit]

    rule_kb = json.loads(Path(args.rule_kb).read_text(encoding="utf-8"))
    system_prompt = build_system_prompt(rule_kb)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    processed = read_processed_ids(output_path)

    print(f"Selected {len(evidence_rows)} evidence rows. Output: {output_path}")
    with output_path.open("a", encoding="utf-8") as out_f:
        for position, row in enumerate(evidence_rows, start=1):
            evidence_id = str(row["evidence_id"])
            if evidence_id in processed:
                print(f"[{position}/{len(evidence_rows)}] evidence_id={evidence_id} skipped")
                continue
            print(
                f"[{position}/{len(evidence_rows)}] evidence_id={evidence_id} "
                f"row={row.get('row_index')} ...",
                end=" ",
            )
            try:
                result, raw_response = call_glm(args, api_key, system_prompt, row)
                record = {
                    "evidence_id": evidence_id,
                    "row_index": row.get("row_index"),
                    "base_row_index": row.get("base_row_index", row.get("row_index")),
                    "session_id": row.get("session_id", ""),
                    "source_type": row.get("source_type", ""),
                    "stable_device_key": row.get("stable_device_key", ""),
                    "group_id": row.get("group_id", ""),
                    "group_size": row.get("group_size"),
                    "sample_weight": row.get("sample_weight"),
                    "teacher_score": row.get("teacher_score"),
                    "teacher_band": row.get("teacher_band"),
                    "rule_family": row.get("rule_family"),
                    "evidence_hash": row.get("evidence_hash"),
                    "is_augmented": bool(row.get("is_augmented")),
                    "augmentation_id": row.get("augmentation_id", ""),
                    "model": args.model,
                    "knowledge_version": args.knowledge_version,
                    "group_scores": {key: result[key] for key in GROUP_SCORE_KEYS},
                    "group_reasons": result["group_reasons"],
                    "raw_response": raw_response,
                }
                out_f.write(json.dumps(record, ensure_ascii=False) + "\n")
                out_f.flush()
                scores = ",".join(str(result[key]) for key in GROUP_SCORE_KEYS)
                print(f"scores=[{scores}] teacher={row.get('teacher_score')}")
            except Exception as exc:
                record = {
                    "evidence_id": evidence_id,
                    "row_index": row.get("row_index"),
                    "base_row_index": row.get("base_row_index", row.get("row_index")),
                    "session_id": row.get("session_id", ""),
                    "model": args.model,
                    "knowledge_version": args.knowledge_version,
                    "teacher_score": row.get("teacher_score"),
                    "error": str(exc),
                }
                out_f.write(json.dumps(record, ensure_ascii=False) + "\n")
                out_f.flush()
                print(f"ERROR: {exc}")


if __name__ == "__main__":
    main()
